tasks:
  - name: Install docker
    become: true
    apt:
      name:
        - docker
          docker-cli
      state: present
    
  - name: Install kubectl
    become: true
    apt:
      name: kubectl
      state: present
  
  - name: Install kubeadm
    become: true
    apt:
      name: kubeadm
      state: present

  - name: Install kubelet
    become: true
    apt:
      name: kubelet
      state: present
